using System.Text.Json.Serialization;

namespace DocxMcp.WordAddin.Models;

/// <summary>
/// Request to start an LLM editing session.
/// </summary>
public sealed class LlmEditRequest
{
    /// <summary>
    /// The document session ID (from docx-mcp).
    /// </summary>
    public required string SessionId { get; init; }

    /// <summary>
    /// User's instruction for the LLM (e.g., "rewrite this paragraph more concisely").
    /// </summary>
    public required string Instruction { get; init; }

    /// <summary>
    /// Current document content (from Word via Office.js).
    /// </summary>
    public required DocumentContent Document { get; init; }

    /// <summary>
    /// Optional: specific path to focus on (e.g., "/body/paragraph[2]").
    /// </summary>
    public string? FocusPath { get; init; }

    /// <summary>
    /// Optional: user's recent logical changes (for context).
    /// </summary>
    public List<LogicalChange>? RecentChanges { get; init; }
}

/// <summary>
/// Document content sent from Word.
/// </summary>
public sealed class DocumentContent
{
    /// <summary>
    /// Full text content of the document.
    /// </summary>
    public required string Text { get; init; }

    /// <summary>
    /// Structured elements (paragraphs, headings, etc.) with IDs.
    /// </summary>
    public List<DocumentElement>? Elements { get; init; }

    /// <summary>
    /// Current selection in Word (if any).
    /// </summary>
    public SelectionInfo? Selection { get; init; }
}

/// <summary>
/// A document element with stable ID.
/// </summary>
public sealed class DocumentElement
{
    public required string Id { get; init; }
    public required string Type { get; init; }
    public required string Text { get; init; }
    public int Index { get; init; }
    public string? Style { get; init; }
}

/// <summary>
/// Information about the current selection in Word.
/// </summary>
public sealed class SelectionInfo
{
    public required string Text { get; init; }
    public int StartIndex { get; init; }
    public int EndIndex { get; init; }
    public string? ContainingElementId { get; init; }
}

/// <summary>
/// A logical change detected from user edits.
/// </summary>
public sealed class LogicalChange
{
    public required string ChangeType { get; init; } // added, removed, modified, moved
    public required string ElementType { get; init; }
    public required string Description { get; init; }
    public string? OldText { get; init; }
    public string? NewText { get; init; }
    public DateTime Timestamp { get; init; }
}

/// <summary>
/// SSE event sent during LLM streaming.
/// </summary>
public sealed class LlmStreamEvent
{
    public required string Type { get; init; }
    public string? Content { get; init; }
    public LlmPatch? Patch { get; init; }
    public string? Error { get; init; }
    public LlmStreamStats? Stats { get; init; }
}

/// <summary>
/// A patch generated by the LLM to apply to the document.
/// </summary>
public sealed class LlmPatch
{
    /// <summary>
    /// Operation: add, replace, remove, move.
    /// </summary>
    public required string Op { get; init; }

    /// <summary>
    /// Target path in the document.
    /// </summary>
    public required string Path { get; init; }

    /// <summary>
    /// Value for add/replace operations.
    /// </summary>
    public object? Value { get; init; }

    /// <summary>
    /// Source path for move operations.
    /// </summary>
    public string? From { get; init; }
}

/// <summary>
/// Statistics at the end of streaming.
/// </summary>
public sealed class LlmStreamStats
{
    public int InputTokens { get; init; }
    public int OutputTokens { get; init; }
    public int PatchesGenerated { get; init; }
    public double DurationMs { get; init; }
}

/// <summary>
/// Report user's changes to the backend for context tracking.
/// </summary>
public sealed class UserChangeReport
{
    public required string SessionId { get; init; }
    public required DocumentContent Before { get; init; }
    public required DocumentContent After { get; init; }
}

/// <summary>
/// Result of processing user changes into logical patches.
/// </summary>
public sealed class UserChangeResult
{
    public required List<LogicalChange> Changes { get; init; }
    public required string Summary { get; init; }
}

/// <summary>
/// JSON serialization context for AOT compatibility.
/// </summary>
[JsonSerializable(typeof(LlmEditRequest))]
[JsonSerializable(typeof(LlmStreamEvent))]
[JsonSerializable(typeof(LlmPatch))]
[JsonSerializable(typeof(UserChangeReport))]
[JsonSerializable(typeof(UserChangeResult))]
[JsonSerializable(typeof(DocumentContent))]
[JsonSerializable(typeof(DocumentElement))]
[JsonSerializable(typeof(SelectionInfo))]
[JsonSerializable(typeof(LogicalChange))]
[JsonSerializable(typeof(LlmStreamStats))]
[JsonSerializable(typeof(List<LlmPatch>))]
[JsonSerializable(typeof(List<LogicalChange>))]
[JsonSerializable(typeof(List<DocumentElement>))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public partial class WordAddinJsonContext : JsonSerializerContext
{
}
