/**
 * Types shared between the Word add-in and the backend.
 */

/** Document element with stable ID */
export interface DocumentElement {
  id: string;
  type: 'paragraph' | 'heading' | 'table' | 'list';
  text: string;
  index: number;
  style?: string;
}

/** Current selection in Word */
export interface SelectionInfo {
  text: string;
  start_index: number;
  end_index: number;
  containing_element_id?: string;
}

/** Document content sent to the backend */
export interface DocumentContent {
  text: string;
  elements?: DocumentElement[];
  selection?: SelectionInfo;
}

/** Logical change detected from user edits */
export interface LogicalChange {
  change_type: 'added' | 'removed' | 'modified' | 'moved';
  element_type: string;
  description: string;
  old_text?: string;
  new_text?: string;
  timestamp?: string;
}

/** Request to start LLM editing */
export interface LlmEditRequest {
  session_id: string;
  instruction: string;
  document: DocumentContent;
  focus_path?: string;
  recent_changes?: LogicalChange[];
}

/** Patch generated by the LLM */
export interface LlmPatch {
  op: 'add' | 'replace' | 'remove' | 'move' | 'replace_text';
  path: string;
  value?: unknown;
  from?: string;
}

/** SSE event from the LLM stream */
export interface LlmStreamEvent {
  type: 'content' | 'patch' | 'done' | 'error';
  content?: string;
  patch?: LlmPatch;
  error?: string;
  stats?: {
    input_tokens: number;
    output_tokens: number;
    patches_generated: number;
    duration_ms: number;
  };
}

/** Report user changes to backend */
export interface UserChangeReport {
  session_id: string;
  before: DocumentContent;
  after: DocumentContent;
}

/** Result of processing user changes */
export interface UserChangeResult {
  changes: LogicalChange[];
  summary: string;
}

/** Configuration for the add-in */
export interface AddinConfig {
  backendUrl: string;
  sessionId: string;
  autoTrack: boolean;
  debounceMs: number;
}
